### PR TITLE
correct example

### PR DESCRIPTION
**Pull request by jvoigtlaender**

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Also, actually I'm pretty sure the printout of `groupBy .groupId [mary, jack, jill]` would be `Dict.fromList [(1, [jill, mary]),(2, [jack])]', not `Dict.fromList [(2, [jack]), (1, [jill, mary])]'.

**Comment by Skinney** [comment]
You are entirely correct about that (as evidenced in the test). Would you mind updating your commit to reflect this?

**Comment by jvoigtlaender** [comment]
Well, the test doesn't reflect that, since it is testing whether `toList (groupBy .groupId [mary, jack, jill])` is equal to `[(1, [jill, mary]),(2, [jack])]`, which is not the same as testing whether  `groupBy .groupId [mary, jack, jill]` is equal to `Dict.fromList [(1, [jill, mary]),(2, [jack])]`. In fact, if equality on `Dict`s were reliable, both of these:
* `groupBy .groupId [mary, jack, jill] == Dict.fromList [(1, [jill, mary]),(2, [jack])]`
* `groupBy .groupId [mary, jack, jill] == Dict.fromList [(2, [jack]),(1, [jill, mary])]`

should be true (but still, actually printing out the result of the `groupBy`-call would give the first of the possible two right-hand sides).

But in any case, yes, I'll change the doc comment.

**Comment by jvoigtlaender** [comment]
Done. I guess you can simply squash the two commits on merge.

**Pull request merged**
